SQL Parser
AlexValder/DB_Labs pull request #5
Opened 2021-03-18 18:34 UTC by AlexValder

2021-03-18 18:58 UTC, ArthurMamedov approved these changes

2021-03-20 14:25 UTC, ArthurMamedov commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlSelect.cs
> +        public List<string>? Fields { get; }
The same irritating question mark.

2021-03-20 14:25 UTC, ArthurMamedov commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlSelect.cs
> +        public string Table { get; }
public new string Table { get; } ?

2021-03-20 14:32 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlInsertInto.cs
> +        public List<string>? Fields { get; }
To show that this property might be null in ready object... And Values should always have a value...

2021-03-20 14:32 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlUpdate.cs
> +        public class SqlUpdate : SqlCommand {
4 spaces?

2021-03-20 14:33 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlSelect.cs
> +        public string Table { get; }
I'll fix...

2021-03-20 15:10 UTC, ArthurMamedov commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlInsertInto.cs
> +        public List<string>? Fields { get; }
Ok, well...

2021-03-20 15:12 UTC, ArthurMamedov commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlUpdate.cs
> +        public class SqlUpdate : SqlCommand {
Yep...

2021-03-20 17:20 UTC, ArthurMamedov requested changes

2021-03-20 17:20 UTC, ArthurMamedov commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlUpdate.cs
> +                $"WHERE {Condition.Value.Item1} {Condition.Value.Item2.ToString()} {Condition.Value.Item3}" :
Replace with: `$"WHERE \"{Condition.Value.Item1}\" {Extension.ToString(Condition.Value.Item2)} \"{Condition.Value.Item3}\""`

2021-03-20 18:57 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/Operation.cs
> +        public static string ToString(this Operation @op) => @op switch {
Done

2021-03-20 18:57 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlInsertInto.cs
> +            Fields != null ? $"({string.Join(',', Fields)})" : "";
Done

2021-03-20 18:58 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlDelete.cs
> +                ? $" WHERE {Condition.Value.Item1} {Condition.Value.Item2} {Condition.Value.Item3}"
Done

2021-03-20 18:58 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlInsertInto.cs
> +        private string GetValues() => $"({string.Join(',', Values)})";
Done

2021-03-20 18:58 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlUpdate.cs
> +                Set.Select(pair => $"{pair.Item1} = {pair.Item2}"));
Done

2021-03-20 18:58 UTC, AlexValder commented on DBLab2/DBLab2/ConsoleController/SqlCommands/SqlUpdate.cs
> +                $"WHERE {Condition.Value.Item1} {Condition.Value.Item2.ToString()} {Condition.Value.Item3}" :
Done

2021-03-22 21:23 UTC, ArthurMamedov approved these changes

2021-03-22 21:23 UTC, merged