GlobalContiner
AlexValder/DB_Labs pull request #7
Opened 2021-03-20 18:41 UTC by SoloPashaS

GlobalContainert added:)))))))))))

2021-03-20 18:52 UTC, ArthurMamedov requested changes

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["Book"] = new string[] { "Title", "Year", "PublisherId", "Publisher" },
- Publisher

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["BookAuthor"] = new string[] { "BookId", "AuthorId", "Book", "Author" },
- Book

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["Cathedra"] = new string[] { "FacultyId", "Name", "Faculty" },
- Faculty

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["Group"] = new string[] { "Number", "SpecialityId", "CathedraId", "Cathedra", "Speciality" },
- Cathedra
- Specialty

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +                "TeacherCards", "LibraryEmployees"},
Take this off.

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["LibraryEmployee"] = new string[] { "FirstName", "LastName", "PositionId", "Position" },
- Position

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["Program"] = new string[] { "" },
Take this off.

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["Speciality"] = new string[] { "Name", "Number", "FacultyId", "Faculty" },
- Faculty

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["Student"] = new string[] { "FirstName", "LastName", "Year", "GroupId", "Group" },
- Group

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +                "BookId", "LibraryEmployeeId", "Student", "Book", "LibraryEmployee" },
- Book
- Student
- LibraryEmployee

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +            ["Teacher"] = new string[] { "FirstName", "SecondName", "CathedraId", "Cathedra" },
- Cathedra

2021-03-20 18:52 UTC, ArthurMamedov commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +                "BookId", "Teacher", "LibraryEmployee", "Book"}
- Teacher
- LibraryEmployee
- Book

2021-03-20 20:21 UTC, AlexValder commented on DBLab2/DBLab2/Common/GlobalContainer.cs
> +        private static Dictionary<string, string[]> DictOfLists = new Dictionary<string, string[]>
`public static`

2021-03-23 06:52 UTC, ArthurMamedov approved these changes
Nice done.

2021-03-23 06:52 UTC, merged